### PR TITLE
Singularity extra

### PR DESCRIPTION
**Pull request by tpetr**
@jhaber this is the rest of the dropwizard-y boilerplate in Singularity -- thoughts on including it?

### CODE REVIEW

**Comment by jhaber** [comment]
Should the providers be bound in a module? Otherwise they have no effect right?

**Comment by tpetr** [comment]
i was thinking you'd wire up the Providers in your [service's main module](https://github.com/HubSpot/Singularity/blob/master/SingularityService/src/main/java/com/hubspot/singularity/SingularityMainModule.java#L134-L135), but if it makes sense i can make a module for them

**Comment by tpetr** [comment]
@jhaber ^ going down the `EnvironmentAwareModule` track as discussed in person

**Comment by jhaber** [comment]
Sweet

**Pull request merged**
